### PR TITLE
test comment

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
type bug-fix

**Comment by smuzaffar** [comment]
@ianna , do you get this message

**Comment by smuzaffar** [comment]
Ianna, if you have received the previous message then you should also have received this message

**Comment by smuzaffar** [comment]
If you have received my previous two comments then go ahead and un-subscribe

**Comment by ianna** [comment]
ok, the thread is muted

**Comment by smuzaffar** [comment]
Did you get the notification now?

**Comment by ianna** [comment]
nope

**Comment by ianna** [comment]
yes, I did :-)

**Comment by smuzaffar** [comment]
If you have un-subsribed then you should not get notification for these messages

**Comment by smuzaffar** [comment]
ah OK, may be because you have commented on the PR

**Comment by ianna** [comment]
now I've unsubscribed

**Comment by smuzaffar** [comment]
ok, some this messages should not reach you then

**Comment by smuzaffar** [comment]
and if I mention your name e.g. @ianna then you might get the notification... right?

**Comment by ianna** [comment]
yes, I've got all of them

**Comment by smuzaffar** [comment]
hummm, ok so it did not work. I guess once you have contributed to the issue e.g. added a comment then you might not be able to un-subscribe

**Comment by smuzaffar** [comment]
this message should not reach you

**Comment by smuzaffar** [comment]
but this message as it has your name @ianna should reach you

**Comment by smuzaffar** [comment]
and this message should also not reach you as you still be un-subscribed

**Pull request closed without merging**
